fix typo
seunghyun-24/nest-study pull request #11
Opened 2024-11-18 12:47 UTC by seunghyun-24

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [ ] New feature
- [x] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
week2 전반적인 피드백 반영 및 ci 돌아가라 얍

## Why
- 어떤 이유로 작업하셨나요?(Optional)
오류나서용..

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-18 13:35 UTC, worjs commented
@seunghyun-24 이미 잘못 merge된 코드가 너무 많아서 main 브랜치좀 조금 되돌려두려하는데 괜찮으실까요?

2024-11-18 13:36 UTC, seunghyun-24 commented
ㅋㅋㅋㅋㅋㅋ 저도 방금 작업하면서 알게되었어요 ... ㅠㅠ 상관 없습니당

2024-11-18 14:01 UTC, worjs requested changes
리뷰 드렸습니다~
Post /events 관련 피드백이 일부 반영이 안되어있네요. 그때 PR 확인해보시면 당시 코멘트들 있으니 참고해서 같이 반영 부탁드립니닷

2024-11-18 14:01 UTC, worjs commented on src/event/event.controller.ts
> +    console.log(query);
콘솔 삭제!

2024-11-18 14:01 UTC, worjs commented on src/event/event.controller.ts
> +  }
코드 전반에서 event"ID"와 event"Id" 가 혼용되고 있습니다!
둘 중에 하나로 통일하는게 좋을 것 같네요!

2024-11-24 12:49 UTC, seunghyun-24 commented on src/event/event.repository.ts
> +      },
어라라..

2024-11-24 12:50 UTC, seunghyun-24 commented on src/event/event.repository.ts
> +  }
앟 ㅠㅠ 객체로 담아서 보낼 때의 단점이 있을까요?

2024-11-24 12:52 UTC, seunghyun-24 commented on src/event/event.repository.ts
> +  }
지금 보니 그렇네요.. ㅠㅠcount 알기 전에 무지성으로 위에거 짜두고, 코파일럿 권유에 따라........  저런 코드가 발생했던 것 같습니다

2024-11-24 12:54 UTC, seunghyun-24 commented on src/event/event.service.ts
> +    }
살짝.. 변수 안써버릇하는 코딩스타일이 그대로 묻어나서 ㅠㅠ.. 보통 협업할 땐 / 회사용 코드(?) 쪽은 가독성 좋게 변수명 하나씩 선언해서 깔끔하게 관리해주는 쪽이 더 많은가요?? 아님 회바회부바부 차이인지.. 뭔가 당연한 질문이라면 죄삼당.. ㅠㅅㅠ

2024-11-24 12:57 UTC, seunghyun-24 commented on src/event/event.repository.ts
> +  }
dead code 찾아주셔서 감사합니당

2024-11-24 13:00 UTC, seunghyun-24 commented on src/event/event.controller.ts
> +  }
감사합니당!

2024-11-24 13:19 UTC, seunghyun-24 commented on src/event/event.repository.ts
> +  }
넹!

2024-11-24 13:20 UTC, closed without merging

2024-11-24 16:07 UTC, worjs commented on src/event/event.repository.ts
> +  }
음... 굳이 말하자면 복잡함... ?
넘길 때도 객체로 말아서 넘겨야하고 타입 표현도 조금 지저분해진다고 생각해요.

저는 보통 아래의 경우에 객체로 묶어서 넘깁니다
1. 인자 수 4~5개 이상
2. 함수 이름과 인자를 보고 바로 인자들의 역할을 이해하기 어려운 경우
3. 인자로 넘기는 데이터의 구성이 자주 바뀌는 경우

우리 코드에서는 데이터 생성이나 업데이트하는 CreateEventData나 UpdateaEventData 이런애들이 좀 해당이 되는 것 같네용

2024-11-24 16:13 UTC, worjs commented on src/event/event.service.ts
> +    }
```
 if (await this.eventRepository.isUserJoinedToEvent({ eventID, userID })) {
      throw new BadRequestException('이미 참여한 Event입니다.');
    }
```

음 모든 회사들이 그렇게 하는지는 잘 모르겠지만 저는 협업할 때 좋은 코드는 아니라고 생각해요!
일단 변수를 선언해서 나눠주면 코드의 호흡(?)을 한번씩 쉬어주고 간다고 해야하나....

지금 코드에서는 한 줄에 2가지의 내용이 담겨있는 셈인데, 이걸 변수를 만들어서 할당해주면 읽는 사람 입장에서는
`const isJoined = await this.eventRepository.isUserJoinedToEvent({ eventID, userID })`
이거 먼저 이해하고, `if(isJoined)` 이걸 이해하면 되니까 따라오기가 좀 편해지는거죠!

isJoined라는 변수명에도 또 의미가 담겨있으니까 이 코드를 처음보는 다른 개발자들이 더 이해하기 쉬워지구요!