Week2/revolution
seunghyun-24/nest-study pull request #12
Opened 2024-11-24 13:22 UTC by seunghyun-24

## Type
PR 종류를 확인해 주세요.
- [x] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [] Etc

## Purpose
- 어떤 목적의 작업인가요?
feedback2 브랜치에서 작업한 피드백 반영

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-24 15:57 UTC, worjs commented
어 혹시 왜 브랜치를 또 만드신건가요 .. ??? 이번엔 거기에 작업해도 될거같았는데

2024-11-24 15:59 UTC, seunghyun-24 commented
그 약간 .. pr 날리고 나서야 아 브랜치 왜 또 팠지 하는 .. 거였는데 뒤에거 쭉 하려다가 한 번 갈아엎을 것 같아서 바쁘시면 해당 pr 스킵하셔도 괜찮을 것 같습니다!! 죄송합니다 ㅠㅠㅠ

2024-11-24 16:17 UTC, worjs commented
어어어 괜찮긴 한데 혹시 브랜치 어려우시면 도와드리고싶어서요 ㅋㅋㅋㅋ
상황 설명해주시면 뭔가 제가 도와드릴게 있을까 싶어서....

2024-11-25 01:06 UTC, seunghyun-24 commented
그냥.. 수정하고 커밋 날리고 여기 다시 수정했습니다! 정도의 코멘트만 달면 알림이 충분히 가는걸까요,,? 약간 아예 협업 작업에서 브랜치 룰 정해진 상태에 pr 날리고 남들이 빠꾸먹이면 재pr 하는 작업들만 하다가,, 셀프pr 하는 느낌이라 좀 난해해서 그런거라 ㅠㅠ 깃 제대로 공부 안해서 그런겁니다,, ㅋㅋ큐ㅠㅠ 감사해요!!

2024-11-25 03:35 UTC, worjs commented
아아 그러니까 원래 하셨던 곳에서는 리뷰를 올리면 해당 PR을 닫고 다시 새로운 브랜치를 파서 PR을 올렸다는 말씀이신가요??

2024-11-25 03:51 UTC, worjs commented
근데 이 기능자체가

"제가 이런 코드를 고치거나 새로 만들었는데 main에 머지해도 될까요?" 라고 질문하려는 목적이거든요
그래서 리뷰어가 Approve를 해주면 이제 머지를 하는거고, Change Request를 받으면 수정해서 올려달라는 뜻이구요.

피드백을 받았다면, 같은 브랜치에서 더 수정해서 커밋해서 푸시하면 됩니다.
그리고 다시 리뷰를 요청하면 리뷰어가 와서 다시 리뷰를 하구요.

이렇게 해서 최초에 올린 코드 변경사항에 대해서 리뷰어와 작성자가 같이 점검이 끝나면 짠 하고 머지를 하는거죠

2024-11-25 03:55 UTC, seunghyun-24 commented
그쵸.. 원래 그런 기능인데 다시 생각해보니까 워낙 급박하게 작업하던 환경이라 개발하면서 이것저것 바뀌고 버튼 만들고 수정하면 거기서 뭔갈 하는게 아니라 기능 자체를 추가해야 한다거나 minor 수정보단 major 수정이 컸어서 아예 그랬던 것 같네용..  

애초에 작업 바뀌는거 보는게 같은 브랜치에서 보기 쉬울텐데..! 친절하게 설명해주셔서 감사합니다 ㅎㅎ!!

2024-11-25 04:04 UTC, worjs requested changes
이번엔 진짜 찐 여기서 수정하고 끝내보시죠!!!

2024-11-25 04:04 UTC, worjs commented on src/event/event.repository.ts
> +  }> {
요기도 매개변수로 바꾸시거나 별도의 타입으로 만들어주시면 좋을듯

근데 이 함수 같은 경우에는 저는 그냥 아무것도 리턴하지 않아도 좋다고 생각해요.
어차피 
```
    id: number;
    createdAt: Date;
    updatedAt: Date;
    eventId: number;
    userId: number;
```
얘네들이 당장 api에서 리턴으로 내려줘야 한다던가... 쓸모가 있지는 않아서요

2024-11-25 04:04 UTC, worjs commented on src/event/event.repository.ts
> +        userId: data.userID,
사소한거긴 한데, 코드 전체적으로 "ID"와 "Id"가 혼용되고 있습니다.
이런게 쌓이고 쌓이면 누군가 오타로 실수할 여지가 생겨서 하나로 통일해주시는게 좋아요.

2024-11-25 04:06 UTC, worjs commented on src/event/event.repository.ts
> +  }
아 그러니까 현재 eventJoin 테이블에서 참여자 관리를 하는데, 모임을 생성했다는건 호스트도 가입했다는 의미니까요
eventJoin을 하나 생성해주셔야 하는데, 예전에 별도의 함수로 구현하셔서 드린 코멘트입니당

2024-11-25 04:30 UTC, seunghyun-24 commented on src/event/event.repository.ts
> +  }
헛.. 수정 했던 부분인데 뭔가 저번에 머지 잘못하면서 꼬여서 하나도 반영이 안됐던 부분들..인 것 같네요 ㅠㅠ 감사합니다!

2024-11-25 04:31 UTC, seunghyun-24 commented on src/event/event.service.ts
> +    }
리팩토링 했습니다! 400, 404, 409 관련해서도 제가 맞게 이해했는진 모르겠지만 최대한 구분해서 exception 변경했습니다!

2024-11-25 04:37 UTC, seunghyun-24 commented on src/event/event.repository.ts
> +  }> {
매개변수화 했습니다!

2024-11-25 04:38 UTC, seunghyun-24 commented on src/event/event.repository.ts
> +        userId: data.userID,
통일 완료했습니다! 되게 사소한건데 쌓여서 업보를 이룬다는 걸 체감했습니다

2024-11-25 04:58 UTC, merged