Week3/update event
seunghyun-24/nest-study pull request #13
Opened 2024-11-25 03:04 UTC by seunghyun-24

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
모임을 수정하는 API입니다.

## Why
- 어떤 이유로 작업하셨나요?(Optional)
week3 hw 1/3 (https://github.com/worjs/nest-study-eventory/issues/33)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-25 06:12 UTC, worjs requested changes
1. 컨트롤러 부분 주석 풀어주시고
2. CreateEventData처럼 Update도 타입 하나 만들어서 Repository가 API Payload 형태에 의존하지 않도록 변경해주세요!

2024-11-25 06:12 UTC, worjs commented on src/event/event.service.ts
> +    }
startTime이랑 endTime을 우리가 input으로 받았으니까 그거에 관한 처리가 필요할 것 같네요!

startTime만 왔다면 기존 endTime과의 관계를 고려해주어야 할테고, 반대도 있고, 둘 다 새로운 값이 올 수도 있구요

2024-11-25 06:12 UTC, worjs commented on src/event/event.service.ts
> +    }
첫번째 예외처리는 이미 시작된 Event를 수정할 수 없다는 메세지가 더 맞을 것 같습니다.

2024-11-25 06:12 UTC, worjs commented on src/event/event.service.ts
> +    }
두번째 예외처리는 기존에 정합성 맞게 잘 들어가 있는 event의 시간들을 비교한거라 일단은 의미없는 코드!

2024-11-25 06:26 UTC, seunghyun-24 commented on src/event/event.service.ts
> +    }
생각을 했..는데 event랑 payload 쪽 부분을 착각해서 단단히 잘못 짰었네요! 반영하여 수정했습니다!

2024-11-25 09:35 UTC, worjs requested changes
Repository에 있는 updateEvent 함수 매개변수 타입도 생성한 타입으로 바꿔주셔야 합니다~

2024-11-25 10:29 UTC, seunghyun-24 commented on src/event/event.service.ts
> +    }
오오.. 근데 이런 경우에는 startTime이랑 endTime을 맨 밑에서 상수로 받아준 경우와 아닌 경우를 따로 처리해줘야하나요?? 코드 선언은 알겠는데, 활용 방식이 감이 안왔어서요..! 그냥 조건문 하나 더 써서 커밋 했습니당 ㅠㅠ!

2024-11-25 10:42 UTC, worjs commented on src/event/event.service.ts
> +    }
음음 혹시 맨 밑에서 상수로 받아준 경우가 어떤 의미일까요?

2024-11-25 10:44 UTC, worjs commented on src/event/event.service.ts
> +    }
아 일단 저 코드는 시간 관련 로직 들어가기 전에 만드는 변수입니다.
?? 연산자가 앞에 값이 0,"",false,null, unefined 이런애들 오면 뒤에 값으로 쓴다 이런 문법이니까

지금 저 코드는 payload로 넘겨준게 없으면 event.startTime이 저장하고자 하는 startTime 값이다! 라는 의미가 되는거죠

이제부터는 payload에서 온 값이니 event에서 온 값이니 신경쓰지 않고

createEvent에서 했던 것처럼 2개의 시간 예외 검증만 해주면 됩니다.

2024-11-25 10:46 UTC, worjs requested changes

2024-11-25 10:48 UTC, seunghyun-24 commented on src/event/event.service.ts
> +    }
오.. 그냥 써줘도 문제가 없나보군요

2024-11-25 10:49 UTC, seunghyun-24 commented on src/event/event.service.ts
> +    }
엇 그래서 모두 모두 모두 if를 각각각 작성해주었는데, .. 아 그렇군요 그럼 중간에 에러나서 죽어버릴 수도 있겠구나

2024-11-25 10:49 UTC, seunghyun-24 commented on src/event/event.service.ts
> +    }
그렇담 순서를 바꿔서... (?)

2024-11-25 10:50 UTC, seunghyun-24 commented on src/event/event.service.ts
> +    }
해도 문제가 되겠군요.. 역시.. 흠

2024-11-25 10:52 UTC, worjs commented on src/event/event.service.ts
> +    }
사실 더더욱 지저분해지긴 하는데 이렇게 하면 되긴 합니다ㅋㅋㅋㅋ

A&B

!A&B

A&!B

2024-11-25 10:59 UTC, seunghyun-24 commented on src/event/event.service.ts
> +    }
어머 이걸 미리 봤으면 좋았을텐데.. ㅋㅋㅋㅋㅋ ㅠㅠ 이렇게ㅔ 바꾼걸로 반영하면 될까요?

2024-11-25 23:11 UTC, seunghyun-24 commented
지금 이게 표현해주시고자 했던 바가 맞아서,, 머지해도 괜찮을까요? 아님 저 로직으로 바꾸는 쪽이 정확할까요..!!

2024-11-26 00:46 UTC, worjs approved these changes
굳이 복잡한 로직으로 다시 돌릴 필요는 없을 것 같구, 하나만 수정해서 머지해주시면 되겠습니다. 고생하셨어요.

2024-11-26 00:46 UTC, worjs commented on src/event/event.service.ts
> +    }
이 코드는 필요 없을 것 같네요

2024-11-26 23:38 UTC, seunghyun-24 commented on src/event/event.service.ts
> +    }
항상 감사합니다!

2024-11-26 23:41 UTC, merged