prisma 변경
seunghyun-24/nest-study pull request #21
Opened 2024-11-27 00:38 UTC by seunghyun-24

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
모임 지역을 복수로 선택할 수 있도록 변경

## Why
- 어떤 이유로 작업하셨나요?(Optional)
hw4

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-27 02:13 UTC, worjs approved these changes
오케오케 좋습니다

2024-11-27 09:45 UTC, seunghyun-24 commented
복수 선택 가능하게 만들었습니당!

2024-12-02 13:39 UTC, seunghyun-24 commented on src/event/event.service.ts
> +      }
수정해보았습니당!!

2024-12-02 13:52 UTC, worjs requested changes
혹시 update event 메소드 테스트할때 cityIds 업데이트하는거 해보셨나요? 이거 에러 날거같아요

제가 지금 밖이라 확인이 안되는데 확인 부탁드립니다~~

2024-12-02 13:52 UTC, worjs commented on src/event/event.service.ts
> +        }
여기도!

2024-12-02 13:52 UTC, worjs commented on src/event/event.repository.ts
> +
좋긴한데 기존 isCityIdExist라는 함수와 기능이 겹치고 있습니다. 이 함수가 배열만 받도록 하던가, isCityIdExist를 없애는게 맞을 것 같네요.

2024-12-03 17:31 UTC, seunghyun-24 commented on src/event/event.repository.ts
> +
그러게용.. 삭제해줬습니다!

2024-12-04 02:20 UTC, worjs approved these changes
고고!

2024-12-04 05:52 UTC, merged