Assignment/find club
seunghyun-24/nest-study pull request #35
Opened 2024-12-04 08:15 UTC by seunghyun-24

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
클럽을 조회하는 API입니다. 
한 클럽의 정보를 가져올 수 있고, 여러 클럽을 불러올 수 있습니다. 

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-12-04 08:26 UTC, worjs requested changes

2024-12-04 08:26 UTC, worjs commented on src/club/dto/club.dto.ts
> +
지금 클럽원 리스트를 확인할 방법이 없군요.
현재 클럽원 ID 리스트도 DTO 필드로 하나 추가하시죠!

2024-12-04 09:24 UTC, seunghyun-24 commented on src/club/dto/club.dto.ts
> +
근데 DTO 필드를 수정하더라도 기존 clubdata 타입에는 변환이 없는게 맞을까요? 이것저것 건드려보고 있는데 계속 경고를 띄우더라구요 ㅠㅠ !  변환 없이 가는게 맞으면, 제가 뭔가 한두개만 깔짝거려서 뜨는 경고 같아서 쭉 수정하려고요!

2024-12-04 09:31 UTC, worjs commented on src/club/dto/club.dto.ts
> +
지금 조회하는 데이터 타입(ClubData)에는 클럽원 정보가 없죠
그러면 클럽원 정보를 알아올 수 있도록 쿼리할 때 몇 가지 필드를 더 가져와야 합니다.
그럼 ClubData 타입도 그에 맞춰서 변하게 됩니다.

그리고 Dto.from에서는, 가져온 데이터에서 클럽원 정보를 빼서 새로운 필드에 넣어서 내려주면 되겠습니다.

2024-12-05 08:22 UTC, seunghyun-24 commented on src/club/dto/club.dto.ts
> +
앗역시..! 감사합니다!!

2024-12-05 09:59 UTC, seunghyun-24 commented
type, dto 쪽 추가해봤습니다!

2024-12-05 14:24 UTC, worjs approved these changes

2024-12-05 23:55 UTC, seunghyun-24 commented on src/club/club.controller.ts
> +
제가.. 맞게 이해한 건 지 모르겠는데 한 번 dto 만들어서 해당 dto 활용하는 코드 작성해봤습니다! 객체 리턴이 중요한데 역시 서비스 돌아가는 전반적인 구조를 잘 모르겠어서 어렵네요 ㅠㅠ..! 상황도 상정해 주셨는데 좀 더 공부해보겠습니다!

2024-12-06 03:32 UTC, worjs requested changes

2024-12-06 03:32 UTC, worjs commented on src/club/dto/club.dto.ts
> +  }
`ClubDto.fromMember(club)`
의 결과물로는 ClubDto가 기대되는 편입니다.

그냥 여기서 바로 꺼내도 좋을듯? 
club.map((club) => club..어쩌구..)

2024-12-06 03:32 UTC, worjs commented on src/club/club.service.ts
> +    }
이렇게 조회한 결과물을 리턴하는거면, 실제 멤버가 아니라 대기자들까지 member로 구분없이 리턴되는 것 같습니다.

2024-12-06 03:32 UTC, worjs commented on src/club/club.controller.ts
> +  }
/members로 끝나는 GET 메소드기 때문에,

실제 리턴 결과로는 member ID의 배열이 온다기보단 member의 정보 배열이 와야 자연스럽습니다.
UserDto를 재활용해보셔도 좋을듯

2024-12-06 03:32 UTC, worjs commented on src/club/club.repository.ts
> +      members: club.clubJoin.map((join) => ({ userId: join.userId })),
흠 이전 리뷰에서 제가 챙겼어야 했네요.
clubJoin에서 단순히 userId만 가져온 다음에 member다! 라고 리턴해버리면 클라이언트 입장에서는 이 사람이 대기자인지 실제 멤버인지에 대해 확인할 방법이 없어져버립니다.

1. 진짜 member만 조회해서 내려주거나
2. status 정보까지 같이 내려주거나

둘 중의 하나의 방법을 정하는게 좋겠습니다.

또, 위와같이 memberId만 주는 상황이라면 members가 아니라 memberIds 와 같이 정보를 명확하게 명시해주세요.

혹은
```
 members : {
   id: number;
} [];
```
와 같이 별도의 객체로 선언해줄 수도 있구요.

2024-12-06 05:40 UTC, seunghyun-24 commented on src/club/club.repository.ts
> +      members: club.clubJoin.map((join) => ({ userId: join.userId })),
members에 status도 한 번 넣어주었습니당

2024-12-06 05:40 UTC, seunghyun-24 commented on src/club/club.controller.ts
> +  }
이름 변경했습니다

2024-12-06 09:51 UTC, worjs requested changes

2024-12-06 09:51 UTC, worjs commented on src/club/dto/club.dto.ts
> +}
파일 분리 할까요?

2024-12-06 09:51 UTC, worjs commented on src/club/dto/club.dto.ts
> +  }
이거 사용중인가요 어디선가?

2024-12-06 09:51 UTC, worjs commented on src/club/club.controller.ts
> +    @Query('status') status: ClubJoinStatus,
쿼리로 status를 조건으로 넘겨줄 수 있게 하셨군요! 좋은 것 같습니다.
이거 제가 궁금한건데, 여기서 status로 ClubJoinStatus Enum 값이 아닌 다른 string을 주면 어떻게 되는지 확인해주실 수 있나요? + 아예 빈 값을 주었을 때도 에러가 날지 안날지 확인이 필요해 보이네요.

만약에 잘 안된다면 기존 EventQuery class처럼 별도의 class로 하는게 나을 수도 있습니다.

2024-12-06 09:51 UTC, worjs commented on src/club/club.controller.ts
> +
아 그리고 이전에도 말씀드렸었는데, Reponse Body, 즉 Dto는 배열로 내리시면 안되고 꼭 객체로 해주셔야 합니다.

이 경우에도 {members: ClubMemberDto[]} 라는 Dto를 하나 더 만들어주셔야 함!

2024-12-06 09:51 UTC, worjs commented on src/club/club.repository.ts
> +      })),
이거 이렇게 리턴할거면
차라리 club-data.type을 이렇게 구성하면 저 쿼리를 바로 리턴할 수 있지 않을까요

```
export type ClubData = {
  id: number;
  title: string;
  description: string;
  leaderId: number;
  maxPeople: number;
  clubJoin: { userId: number; status: ClubJoinStatus }[];
```

2024-12-06 09:51 UTC, worjs commented on src/club/payload/create-club.payload.ts
> +  members!: number[];
아하 club 생성할때 멤버들도 한번에 가입시킬 수 있게 하려고 하셨군요

1. `members`보단 `memberIds`로 하는게 더 적절한 이름으로 보입니다.
2. (Service에서) 이 userId들은 실제로 존재하는 유저인지 검증이 필요합니다.
3. (Repository에서) 이 userId들을 추가하는 로직이 빠져 있습니다.
4. 만약에 클라이언트가 멤버원 명단에 leader의 id를 빼먹는다면 DB 정합성이 깨질 수 있으니, 이 부분을 처리해줄 필요가 있어 보입니다. member 명단에 leader가 없으면 에러를 뱉는다던가, 빠지고 왔다면 토큰에서 꺼낸 leaderId를 내가 대신 넣어준다던가...

2024-12-06 09:51 UTC, worjs commented on src/club/dto/club.dto.ts
> +  })
description이 바뀌지 않았군요

2024-12-06 09:57 UTC, seunghyun-24 commented on src/club/dto/club.dto.ts
> +}
고민고민 했었는데 ㅠㅠ 분리하겠습니다!

2024-12-06 10:01 UTC, seunghyun-24 commented on src/club/dto/club.dto.ts
> +  }
이거 아이디만 가져오고 싶은 상황이 있을까봐 구현해뒀는데.. 뒤에서 구현 바뀌면서 (원래 Id만 처리하는 로직이 있어서 그 용도로 사용하려고 했던 것..일 것 같아요) 필요성 적어진 것 같긴 합니다. 일단 주석 처리해두고 추후 사용 로직 없으면 삭제하겠습니다!

2024-12-06 10:02 UTC, seunghyun-24 commented on src/club/dto/club.dto.ts
> +  })
디테일.. 감사합니다 😊 ☺️

2024-12-06 10:26 UTC, seunghyun-24 commented on src/club/club.controller.ts
> +    @Query('status') status: ClubJoinStatus,
헉 에러 나는거 확인했습니다! 
query 관련 더 해줬습니다!

2024-12-06 10:30 UTC, seunghyun-24 commented on src/club/club.controller.ts
> +
허거덩 이제야 이해했습니다!!! 감사해요!!

2024-12-06 10:47 UTC, seunghyun-24 commented on src/club/club.repository.ts
> +      })),
오.. 생각도 못했던 방법이에요.
근데 club-data.type에는 뭔가 members라는 저 상태로 두고 싶기도 하고, (club-data에 clubJoin 라는 이름을 두는게 마음에 들지 않는다는 사소한 이유입니다 ㅋㅋ ㅠㅠ ) 예쁘진 않지만 clubJoin을 매핑해서 members가 구성된다는 로직이 한번에 보이는 저 코드 구조가 좀 더 마음데 드는데 비효율적이어서 고치는 쪽이 더. ㅏ을까요?

2024-12-06 11:20 UTC, worjs commented on src/club/club.repository.ts
> +      })),
오호
그러면 그대로 가시죠

2024-12-06 13:47 UTC, seunghyun-24 commented on src/club/payload/create-club.payload.ts
> +  members!: number[];
뭔가 구현한 것 같긴 한데.. 적어주신 걸 제대로 이해했는지 모르겠네욥 ㅠㅅㅠ 다른 곳에 다 구현이 된 느낌이라..

2024-12-06 16:01 UTC, worjs requested changes

2024-12-06 16:01 UTC, worjs commented on src/club/query/club-join-status.query.ts
> +export class clubJoinStatusQuery {
클래스 이름은 PascalCase!

2024-12-06 17:07 UTC, seunghyun-24 commented on src/club/club.service.ts
> +    }
넵..!

2024-12-06 17:07 UTC, seunghyun-24 commented on src/club/query/club-join-status.query.ts
> +export class clubJoinStatusQuery {
넹!

2024-12-07 02:16 UTC, worjs approved these changes

2024-12-07 02:55 UTC, merged