Assignment/get club event
seunghyun-24/nest-study pull request #39
Opened 2024-12-06 09:05 UTC by seunghyun-24

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
클럽 전용 모임을 조회하기 위한 작업입니다.
작업 중 방향성이 맞는지 여쭤보기 위해 선pr 날립니다.
- [ ] event 함수에 clubId 관련 type 추가
- [ ] club delete 기능에 시작된 event가 없는지 체크
- [ ] user 탈퇴 시 참여한 event에서 함께 나가게 만들기 
- [ ] user 탈퇴 시 참여한 event가 시작했을 경우 user의 club 탈퇴 막기 

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-12-06 09:06 UTC, seunghyun-24 commented
지금 main과 뭔가 통합이 일어나지 않은 상태인지 ㅠㅠ.. event 함수에서 삭제한 함수가 남아있는 상태입니다.. ㅠㅅㅠ 
event 관련 폴더에서 clubId 쪽 조회 기능 구현 방향성이 맞는지, 아님 club함수에서 event도 다뤄야하는지 등을 먼저 알고 싶어 pr 날렸습니다..!

2024-12-06 09:31 UTC, worjs commented
클럽 모임의 경우에 로직이 크게 다르다면 새로 만드는게 좋겠지만, 간단히 추가하는 정도로 해결 가능하다면 기존 모임에서 구현할 수 있겠죠!
느끼기에 더 공수가 적고 합리적인 방향으로 해주시면 됩니다!

2024-12-06 09:52 UTC, seunghyun-24 commented
앗 이미 구현 해둔 상태입니다! deleteClub 수정하다보니 만든거라.. 해당 분기 pr 닫고 같이 봐주시면 감사하겠습니다!

2024-12-06 10:05 UTC, worjs requested changes

2024-12-06 10:05 UTC, worjs commented on src/event/event.controller.ts
> +  }
1. 음? 이거 테스트 해보신거 맞아요???
2. 클럽 전용 이벤트 목록 조회를 대표할만한 url은 2가지입니다.
    1. GET /events?clubId
    2. GET /clubs/:clubId/events 
    둘 중 한가지로 하시면 될듯!

2024-12-06 13:50 UTC, seunghyun-24 commented on src/event/event.controller.ts
> +  }
헉 이거 다른 데서 브랜치랑 왔다갔다 하면서 맨 처음 수도코드 작성한 버전으로 올라갔네요.. ㅠㅠ 담엔 좀 더 꼼꼼하게 확인해서 올리겠습니다..!

2024-12-06 23:40 UTC, seunghyun-24 commented on src/club/club.service.ts
> +    await this.clubRepository.deleteClub(clubId);
넵..!

2024-12-07 03:45 UTC, worjs requested changes

2024-12-07 03:45 UTC, worjs commented on src/club/club.repository.ts
> +      }
한개 이상의 모임이 진행되었다는 이유로 삭제가 제한되면 안됩니다ㅎㅎ,,,

이미 시작된 클럽 Event는 두고 클럽만 삭제되는 것이구요,
그럼 그 event는 이제 아카이브된 것으로, 당시 참가자만 조회할 수 있게 됩니다. 기록처럼요

2024-12-07 03:45 UTC, worjs commented on src/event/type/event-data.type.ts
> +  clubId?: number;
여기도 `clubId: number | null;`

2024-12-07 03:45 UTC, worjs commented on src/event/dto/event.dto.ts
> +      clubId: event.clubId || null,
ClubData 타입의 설정이 잘못된 것이므로 여기도 고쳐야 하겠습니다

2024-12-07 03:45 UTC, worjs commented on src/club/club.repository.ts
> +      });
event를 지운다고 했을 때, 이미 해당 모임에 가입한 사람도 있을테니, eventjoin들도 고려해야 합니다.

꼭 테스트 해보셔야 합니다ㅠㅠ

2024-12-07 03:45 UTC, worjs commented on src/club/club.repository.ts
> +      }
트랜잭션의 대상은 최대한 write 쿼리만으로 해주시는게 좋습니다!

트랜잭션은 DB에 많은 부담을 줍니다. 내가 트랜잭션으로 묶어둔 쿼리가 모두 commit 되기 전까지 다른 쿼리들이 정상적으로 처리되지 않기 때문입니다. 많이 잡고 있을 수록 이후 서비스가 성장했을 때 병목이 될 가능성이 높죠.

만약 write read write 순서대로 진행되어야 하는 상황이라면 어쩔 수 없지만 이 경우에는 read 쿼리는 트랜잭션 밖으로 빼는게 좋겠습니다.

2024-12-07 03:48 UTC, seunghyun-24 commented on src/club/club.repository.ts
> +      }
ㅠㅠ 그렇군요..

2024-12-07 08:10 UTC, worjs requested changes
여기 PR에서 계속 처리하는 것도 좀 정신이 없어서... delete까지만 구현하고 앞으로는 api당 하나로 좀 부탁드릴 수 있을까요..

2024-12-07 08:10 UTC, worjs commented on src/club/club.repository.ts
> +  }
생각해보니까 저번에 탈퇴 불가로 구현하셨을때 드렸어야 하는 코멘트인데 브랜치들이 좀 섞였어서 제가 이전에 말씀드린줄 알고 안드린 코멘트가 있네요... 아래 참고!

-------------------------
사실 클럽을 삭제할 때 단순히 삭제하기가 힘듭니다.

클럽 모임에 FK조건이 걸려있기 때문에 그냥 클럽을 지우려고 하면 클럽 모임들도 전부 지워야 합니다.
그러면 기존 유저들은 클럽이 없어졌다는 이유로 자기가 참여했던, 혹은 만들었던 모임들이 전부 없어지게 됩니다.

이 부분을 잡아내서 어쩌라는건가요? 라고 질문하는게 출제의도(?) 였는데,

아무튼 요거는 아카이빙이라는 개념을 도입해서 해결하기로 합니다.

- 클럽을 삭제할 때, 이미 시작된 모임들은 아카이빙됩니다.
- 클럽을 삭제할 때, 시작되지 않은 모임들은 삭제합니다.
- 아카이빙된 모임은 모임 참가자만 조회할 수 있습니다.
- 아카이빙된 모임의 리뷰는 모임 참가자만 조회할 수 있습니다.

이 부분을 고려하실 때 현재 스키마로는 어려울 수 있기 때문에 스키마 변경도 고려해보시면 좋을듯!

2024-12-07 09:15 UTC, seunghyun-24 commented on src/club/club.repository.ts
> +  }
아마.. 원래는 ㅠㅠ delete를 그냥 하나라도 이벤트가 시작했다면 삭제 안되게!로 구현하는 걸 염두에 둔거라 이렇게 복잡해질 줄 몰랐어서요 ㅠㅠ 쩝..

2024-12-07 09:18 UTC, seunghyun-24 commented on src/club/club.repository.ts
> +  }
아카이빙 언급이 언뜻 나왔었는데 스키마 변경하기 머리아파서 스킵했는데 아예 안되는 거였군요.... 반영.. 해보겠습니다 ㅠㅠ

2024-12-08 07:31 UTC, seunghyun-24 commented
prisma update 후 achived조건 추가해주고, clubID를 null로 만들어서 삭제가 될 수 있게끔 만들어 보았습니다..!!

2024-12-08 08:11 UTC, worjs requested changes
오케오케 좋습니다.
딱 하나 DB 조회 관련 코멘트가 있는데, 성능 관점에서 중요한 문제여서.. 이거 하나만 고쳐주시고 다시 요청주세요!!

2024-12-08 08:11 UTC, worjs commented on src/club/club.repository.ts
> +    ]);
어차피 가져오는 event는 해당 club의 모든 events인데, 이걸 startTime에 범위 조건을 걸고 2개로 나눠서 쏘는건 많이 비효율적이라고 생각해요!

오히려 가져온 다음에 startTime 정보를 이용해서 우리 서버에서 나누는게 맞을 것 같습니다.

2024-12-08 08:11 UTC, worjs commented on src/club/club.repository.ts
> +            clubId: null, // NOTE :  FK 제약 조건 해결을 위해 clubId를 null로 설정
제 예상인데 API를 따로 파실 필요는 없고 기존 API를 수정하는 방향으로 가시는게 더 좋을거예요

2024-12-08 11:20 UTC, seunghyun-24 commented on src/club/club.repository.ts
> +            clubId: null, // NOTE :  FK 제약 조건 해결을 위해 clubId를 null로 설정
넵!

2024-12-08 11:22 UTC, seunghyun-24 commented on src/club/club.repository.ts
> +    ]);
반영하여 수정했습니다!

2024-12-08 11:34 UTC, worjs requested changes

2024-12-08 11:34 UTC, worjs commented on src/club/club.repository.ts
> +      }
그러고보니 eventCity도 있네요

2024-12-08 13:05 UTC, seunghyun-24 commented on src/club/club.repository.ts
> +      }
delete했습니당!

2024-12-08 13:07 UTC, worjs commented
갑시다갑시다

2024-12-08 13:07 UTC, worjs approved these changes

2024-12-08 13:21 UTC, merged