func
seunghyun-24/nest-study pull request #42
Opened 2024-12-08 15:05 UTC by seunghyun-24

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
클럽장이 신청자를 승인/거절하는 API입니다.

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-12-08 15:25 UTC, worjs requested changes

2024-12-08 15:25 UTC, worjs commented on src/club/club.controller.ts
> +  @Post(':clubId/members/:memberId')
url!

2024-12-08 15:25 UTC, worjs commented on src/club/club.service.ts
> +    }
에러 메세지 확인 부탁드림!

2024-12-08 15:25 UTC, worjs commented on src/club/club.repository.ts
> +    });
이거 findUnique로 조회 가능할듯??

2024-12-08 15:40 UTC, seunghyun-24 commented on src/club/club.repository.ts
> +    });
앗 바꿨습니당..!

2024-12-08 15:58 UTC, worjs requested changes

2024-12-08 15:58 UTC, worjs commented on src/club/club.controller.ts
> +  @Patch(':clubId/members/:memberId/status')
음 경로 파라미터에 있는 값 사용하지도 않는데 url을 이렇게 할 필요가 있을까요ㅎㅎ,,
이미 request body로만 값을 받고 있는 것 같습니다.

2024-12-08 15:58 UTC, worjs commented on src/club/club.repository.ts
> +      },
이번에는 user의 soft delete 고려가 빠졌네요

2024-12-08 16:12 UTC, seunghyun-24 commented on src/club/club.controller.ts
> +  @Patch(':clubId/members/:memberId/status')
앗.. 그. 얘기셨군요, 음 request body로 처리하는 쪽이 좋을지 경로 파라미터를 활용하는 게 좋을지 모르겠네요 ㅠㅠ 좀 payload 선언이 무의미해진 것 같긴 한데, url로 명확한 쪽이 나은 것 같아 활용하는 방향으로 수정했습니다..!

2024-12-09 02:03 UTC, worjs requested changes

2024-12-09 02:03 UTC, worjs commented on src/club/club.controller.ts
> +  @Patch(':clubId/members/:memberId/status')
request body로 보내는 값이 하나더라도 괜찮습니다!
중요한건 더 합리적인 위치로 값을 위치시키는 것이라고 생각해요.
아무튼 잘해주신듯!

2024-12-09 02:03 UTC, worjs commented on src/club/club.repository.ts
> +      },
요고는요?!?

2024-12-09 04:17 UTC, seunghyun-24 commented
어라.. 왜 저 코드가 있지..?

2024-12-09 04:20 UTC, seunghyun-24 commented on src/club/club.repository.ts
> +      },
여기서 findUnique 로 바꾸면서 soft delete를 아래쪽 select에만 넣었는데 불충분한가요..? 
find first로 하면

`async getClubMemberStatus(
  clubId: number,
  userId: number,
): Promise<ClubJoinStatus | null> {
  const member = await this.prisma.clubJoin.findFirst({
    where: {
      clubId,
      userId,
      user: {
        deletedAt: null, // soft delete 조건 추가
      },
    },
    select: {
      status: true,
    },
  });

  return member?.status ?? null;
}
`

인데 findUnique면 이게 맞지 않나 싶어서요..!

2024-12-09 04:23 UTC, seunghyun-24 commented on src/club/club.repository.ts
> +      },
기존 함수는

`async getClubMemberStatus(
    clubId: number,
    userId: number,
  ): Promise<ClubJoinStatus | null> {
    const member = await this.prisma.clubJoin.findUnique({
      where: {
        clubId_userId: {
          clubId,
          userId,
        },
      },
      select: {
        status: true,
        user: {
          select: {
            deletedAt: true,
          },
        },
      },
    });

    if (member?.user?.deletedAt === null) {
      return member.status;
    }

    return null;
  }`
  
  였습니다! 일단 다양한 조건을 고려하는 쪽이 중요하다고 생각해서, findFirst로 변경하겠습니다!

2024-12-09 06:39 UTC, worjs approved these changes

2024-12-09 09:56 UTC, merged