branch 이동
seunghyun-24/nest-study pull request #47
Opened 2024-12-11 02:46 UTC by seunghyun-24

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-12-11 03:05 UTC, seunghyun-24 commented
몇 개 안되는 줄 알았는데.. API 별로 따로 작업할 걸 ㅠㅠ 번거롭게 만들어 죄송합니다 ㅠㅠ
그리고 코드 리팩토링의 필요성을 짜면서 느꼈습니당.. 같은 역할 하는 게 여기저기 있더라구요 
이번주 내로 리팩토링 다시 하겠습니다 ㅠㅠ

2024-12-11 03:11 UTC, worjs requested changes
코멘트 한개만 보시면될듯?
이 PR 마무리하면 통과로 하겠습니닷

2024-12-11 03:11 UTC, worjs commented on src/event/event.service.ts
> +
그 getReviews 가보면 유저가 읽을 수 있는 리뷰만 필터링하는 과정 거쳤었죠?
얘도 그게 필요한데 여기는 그게 빠져있네요

2024-12-11 03:41 UTC, seunghyun-24 commented on src/event/event.service.ts
> +
엇 이거 구현하면서 봤는데, 리뷰 필터링 쪽이 좀 제거가 스파게티 코드 같은데 그렇게 해야만 하나요? 지금 event에선 이벤트만 불러오고, 좀 최소화 하는 방향으로 해봤는데 리뷰는 좀 더 복잡해서 그런건지 제가 event를 불충분하게 예외처리한 건지 궁금합니다..!

2024-12-11 04:15 UTC, worjs requested changes

2024-12-11 04:15 UTC, worjs commented on src/event/event.service.ts
> +        }
어떻게 짜던 요구사항에 맞게 동작하는 코드면 사실 상관 없습니다.

다만, 이 방식으로 하면 반복문 안에 쿼리가 있는 구조가 됩니다.
그럼 필터링 대상 이벤트가 만개 정도라고 해봅시다.

위 함수에서만 2만번의 쿼리가 순차적으로 날아가겠죠? DB로 요청보내는 것도 네트워크 요청이니까, 왕복 지연시간을 생각하면 무지무지 느린 api가 됩니다.

아무튼 반복문 안에 쿼리를 넣지 않고 요구사항을 지킬 수 있게 짜시면 어떻게 짜든 상관없습니다~

2024-12-11 06:44 UTC, seunghyun-24 commented on src/event/event.service.ts
> +        }
헉.. 반복문 안좋다고 매번 얘기해주셨는데 또 이렇게 했네요ㅠㅠ 한번에 불러온 뒤. ㅓ리하는 코드로 작업해봤습니다!

2024-12-12 05:01 UTC, worjs approved these changes
고생많으셨습니다~~~~

2024-12-13 04:45 UTC, seunghyun-24 commented
감사합니다!

2024-12-13 04:45 UTC, merged