Week2/post/join event
seunghyun-24/nest-study pull request #7
Opened 2024-11-16 06:21 UTC by seunghyun-24

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
유저가 모임에 참여하는 API 구현

## Why
- 어떤 이유로 작업하셨나요?(Optional)
week2 hw 4/5 (https://github.com/worjs/nest-study-eventory/issues/18)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-16 15:21 UTC, worjs requested changes
확인 부탁드립니다!

2024-11-16 15:21 UTC, worjs commented on src/event/event.service.ts
> +  }
코드가 이해는 가는데, 굳이? 라는 생각이 듭니다.
exists 여부와 startTime값은 id로 Event를 가져오면 해결될 것 같고, 현재 꽉 차있는지 정보는 별도로 eventJoin의 개수를 세는 쿼리를 날려서 가져오면 될 것 같습니다.

Repository의 함수들은 최대한 DB에 요청만 하고 결과를 담백하게(?) 응답만 하는 정도로 하는게 좋습니다. CheckEventStatus라는 이름의 함수를 봤을 때 어떤 걸 해줄지, 코드를 직접 보지 않고서야 이해하기 어렵기도 하고요!

2024-11-16 15:21 UTC, worjs commented on src/event/event.service.ts
> +  }
if - else if - else는
대부분 if문 여러개로 가능합니다!
아닌 경우들도 있긴 한데, 이 api에서 처리해줘야 하는 내용들은 if문 여러개로 해결이 가능해요.

else if 문들을 사용하거나 중첩 if문을 사용하기 전에, 정말 중첩이 필요한 상황인지 고민해보시면 좋을듯!

2024-11-17 00:19 UTC, merged

2024-11-17 00:20 UTC, seunghyun-24 commented on src/event/event.service.ts
> +  }
넵! 순차적으로 트리 구조 그리듯 중첩 되는거 좋아했는데.. 생각해보니 함수 이름만 보고 직관적으로 아는거나, 간단한 코드랑은 거리가 머네요 ㅠㅠ 해당 부분 반영했습니다!

2024-11-17 00:22 UTC, seunghyun-24 commented on src/event/event.service.ts
> +  }
conflict 난걸 수정하다가 얼떨결에 merge 해버렸..습니다