Week2/post/out event
seunghyun-24/nest-study pull request #8
Opened 2024-11-16 07:00 UTC by seunghyun-24

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
유저가 모임에서 나가는 API

## Why
- 어떤 이유로 작업하셨나요?(Optional)
week2 hw 5/5 (https://github.com/worjs/nest-study-eventory/issues/19)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?
 type checker가 에러를 띄우는 부분 (logic적으로 예외가 발생하지 않을 것이나, null 여부를 알 수 없다고 에러를 띄우는..) 쪽에 주석을 달아두었는데, 좀 더 깔쌈한 함수 선언이 불가능하려나 고민이 됩니다.

 코파일럿의 추천에 따라 BadRequestExceptio를 다 띄웠었는데.. ConflictException을 띄웠어야하는건지 ㅋㅋ ㅠㅠ.... status code를 보지 않아서 좀 예외처리들을 잘못해준 것 같아서 수정이 필요한 듯 싶습니다. ㅠ

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-16 15:26 UTC, worjs requested changes
어떤 예외처리를 해야하는지는 확실하게 알고 계신 것 같습니다!
이전 PR과 거의 코멘트 사항이 비슷해서, 그거 참고하셔서 수정 해주시면 될듯!

BadRequestException을 할거냐 ConflicException을 할거냐에 대해서는 2주차 자료에서 구분법을 다루었으니 참조하시면 됩니다만, 많은 프로젝트에서는 그냥 BadRequest로 퉁치는 경향도 있는 것 같아서... 자신있게 이래야 합니다! 까진 말씀 못드릴 것 같아요ㅋㅋㅋ

2024-11-16 15:26 UTC, worjs commented on src/event/event.service.ts
> +        userID === (await this.eventRepository.getEventHostId(eventID))
hostId만 따로 가져올 필요 없이, event를 가져오면 거기서 다 꺼내 쓸 수 있겠죠?

2024-11-17 13:46 UTC, seunghyun-24 commented on src/event/event.service.ts
> +        userID === (await this.eventRepository.getEventHostId(eventID))
넹!

2024-11-18 09:05 UTC, merged

2024-11-18 09:53 UTC, seunghyun-24 commented
앟.. 근데 이전 건 근데 잘못 머지해머렸고 이 브랜치는 뭔가 깃헙 오류 계속 떠있길래 요청을 안드리긴 했었습니다..!! 작업은 다 되어있긴 해요

2024-11-18 09:55 UTC, worjs commented
요 브랜치도 머지가 되어있어서요ㅠㅜㅠ

2024-11-18 09:56 UTC, worjs commented
깃헙 오류 뜨는거는 빌드 테스트 실패한건데, 서버 실행이 안되서 그럴거예요
실행해보고 에러 잡고 올려주셔야 됩니당ㅎㅎ

2024-11-18 09:56 UTC, seunghyun-24 commented
헉 맞아요.. 뒤에거 작업하는데 자꾸 에러뜨길래 임의로.. ㅋㅋㅋ큐ㅠㅠ 그러게요 확인하시는데 반가롭게 만들어 죄삼당 ㅠㅠ

2024-11-18 09:59 UTC, worjs commented
그러면 제가 여기 리뷰 추가로 달아드릴테니, 2주차 feedback 반영한 PR 하나 올려주시면 될것같네요!

아래 글 보시면 깃 꼬인거 잘 푸실 수(?) 있을 것 같습니당 
https://quiet-airplane-930.notion.site/PR-141bbfebc135801f9d39e7c097119647?pvs=4